model_list:
  - model_name: mordomo-simple
    litellm_params:
      model: groq/llama-3.3-70b-versatile
      api_key: "os.environ/GROQ_API_KEY"
      rpm: 30

  - model_name: mordomo-brain
    litellm_params:
      model: groq/llama-3.3-70b-versatile
      api_key: "os.environ/GROQ_API_KEY"
      rpm: 30

  - model_name: gemini-backup
    litellm_params:
      model: gemini/gemini-1.5-flash-latest
      api_key: "os.environ/GEMINI_API_KEY"

router_settings:
  routing_strategy: simple-shuffle
  enable_pre_call_checks: true

general_settings:
  master_key: "os.environ/LITELLM_MASTER_KEY"
  store_model_in_db: false # Garante que ele não use o Prisma (evita travamentos em ARM64)
