services:

  mordomo-financas-contas:
    image: renaneunao/mordomo-financas-contas:latest
    container_name: mordomo-financas-contas
    restart: unless-stopped
    env_file: .env
    networks:
      - mordomo-net
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 256M

  mordomo-financas-pix:
    image: renaneunao/mordomo-financas-pix:latest
    container_name: mordomo-financas-pix
    restart: unless-stopped
    env_file: .env
    networks:
      - mordomo-net
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 256M

networks:
  mordomo-net:
    external: true
